# Generated by Django 4.1 on 2022-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pipe_name', models.CharField(max_length=30)),
                ('Stock', models.IntegerField()),
                ('Grade', models.CharField(max_length=3)),
                ('colour', models.CharField(max_length=15)),
                ('size', models.IntegerField()),
                ('quality', models.CharField(max_length=20)),
            ],
        ),
    ]
